### ISSUE TITLE
Broken SSL preventing updates

### ISSUE THREAD

**Issue by neponn** [iternio/ovms-link#10]
Hi,

I've been using this great script to keep my ABRP live data up to date from OVMS. It's been working brilliantly until about 2 weeks ago, when it just stopped. Looking at the shell, I see some kind of SSL error whenever an update is attempted:

```
E (14103568) mongoose: mg_ssl_if_mbed_err   0x3f8ba090 SSL error: -9984
I (14103608) ovms-duk-util: [sendlivedata2abrp.js:252:OnRequestFail] error="SSL error"
```

I have the Baltimore cert in my trust list. Am I doing something wrong (nothing has changed at my end), or is there something needing fixing?

**Comment by jmariuse** [comment]
Needs a new CA cert for https://api.iternio.com/

GTS CA 1P5

from this page:
https://pki.goog/repository/

**Comment by neponn** [comment]
Thanks @jmariuse, but I’m not quite sure I understand. Is that something I should do, or something the devs need to do? Or…?

**Comment by jmariuse** [comment]
You need to do this. 
In the installation guide, there are instructions on how to add one speciffic CA certificate. You need to add this one in addition, using the same procedure.

**Comment by jmariuse** [comment]
Look under the heading "Install the Baltimore CyberTrust Root Certificate in OVMS" and do the same for the Google cert. GTS CA 1P5 from this page: https://pki.goog/repository/

**Comment by neponn** [comment]
Awesome - thank you @jmariuse - that worked nicely. Interesting to note that I don't think the Baltimore certificate currently listed in the README is required. Looking at the [OVMS source code](https://github.com/openvehicles/Open-Vehicle-Monitoring-System-3/tree/fb0bdde7b420a296bdb7066f1e7eaa12ead71b67/vehicle/OVMS.V3/components/ovms_tls/trustedca), the Baltimore certificate is already installed by default. I've confirmed this by deleting the manually added Baltimore certificate and including the new Google CA certificate, and my connection to APRB works.

**Comment by neponn** [comment]
Resolved in #11

**Comment by aamilev-bg** [comment]
Good day, 
since 21.11.2024 I got similar that my connection with OVMS has been lost also without good reason and I cannot restore it (after many attempts).
Does also I need to renew some Certificate?

**Comment by jmariuse2** [comment]
> Good day, since 21.11.2024 I got similar that my connection with OVMS has been lost also without good reason and I cannot restore it (after many attempts). Does also I need to renew some Certificate?

I can confirm that I lost contact around the same time (10 days ago).  I will try to troubleshoot.

**Comment by jmariuse2** [comment]
The new required cert is GTS Root R4
Cert validity 11/20/24, 7:01:48 PM GMT+1
 
put this in /store/trustedca/r4, including the dashed lines

-----BEGIN CERTIFICATE-----
MIICCTCCAY6gAwIBAgINAgPlwGjvYxqccpBQUjAKBggqhkjOPQQDAzBHMQswCQYD
VQQGEwJVUzEiMCAGA1UEChMZR29vZ2xlIFRydXN0IFNlcnZpY2VzIExMQzEUMBIG
A1UEAxMLR1RTIFJvb3QgUjQwHhcNMTYwNjIyMDAwMDAwWhcNMzYwNjIyMDAwMDAw
WjBHMQswCQYDVQQGEwJVUzEiMCAGA1UEChMZR29vZ2xlIFRydXN0IFNlcnZpY2Vz
IExMQzEUMBIGA1UEAxMLR1RTIFJvb3QgUjQwdjAQBgcqhkjOPQIBBgUrgQQAIgNi
AATzdHOnaItgrkO4NcWBMHtLSZ37wWHO5t5GvWvVYRg1rkDdc/eJkTBa6zzuhXyi
QHY7qca4R9gq55KRanPpsXI5nymfopjTX15YhmUPoYRlBtHci8nHc8iMai/lxKvR
HYqjQjBAMA4GA1UdDwEB/wQEAwIBhjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQW
BBSATNbrdP9JNqPV2Py1PsVq8JQdjDAKBggqhkjOPQQDAwNpADBmAjEA6ED/g94D
9J+uHXqnLrmvT/aDHQ4thQEd0dlq7A/Cr8deVl5c1RxYIigL9zC2L7F8AjEA8GE8
p/SgguMh1YQdc4acLa/KNJvxn7kjNuK8YAOdgLOaVsjh4rsUecrNIdSUtUlD
-----END CERTIFICATE-----

then use the shell and type "tls trust reload"

"tls trust list" should show the new cert
525 byte certificate: r4
  cert. version     : 3
  serial number     : 02:03:E5:C0:68:EF:63:1A:9C:72:90:50:52
  issuer name       : C=US, O=Google Trust Services LLC, CN=GTS Root R4
  subject name      : C=US, O=Google Trust Services LLC, CN=GTS Root R4
  issued  on        : 2016-06-22 00:00:00
  expires on        : 2036-06-22 00:00:00
  signed using      : ECDSA with SHA384
  EC key size       : 384 bits
  basic constraints : CA=true
  key usage         : Digital Signature, Key Cert Sign, CRL Sign

**Comment by aamilev-bg** [comment]
THANK YOU VERY MUCH @jmariuse2,
Now is working again.
Have great and prosperous day ahead!
and HAVE A GREAT AND SMOOTH WEEKEND!...

**Comment by Julienhelme** [comment]
Hi. I tried this r4 but still get ssl error.

E (42943178) mongoose: mg_ssl_if_mbed_err   0x3f82fb08 SSL error: -9984
I (42943208) ovms-duk-util: [lib/abrp.js:61:log] (2025-02-20 08:51:02.000+00:00) ERROR: ABRP error "SSL error"

Does the r4 need to replace one of the certs or can they all just stay in there?
My certs are.
OVMS# tls trust list
Baltimore CyberTrust Root CA
891 byte certificate: Baltimore CyberTrust Root CA
  cert. version     : 3
  serial number     : 02:00:00:B9
  issuer name       : C=IE, O=Baltimore, OU=CyberTrust, CN=Baltimore CyberTrust Root
  subject name      : C=IE, O=Baltimore, OU=CyberTrust, CN=Baltimore CyberTrust Root
  issued  on        : 2000-05-12 18:46:00
  expires on        : 2025-05-12 23:59:00
  signed using      : RSA with SHA1
  RSA key size      : 2048 bits
  basic constraints : CA=true, max_pathlen=3
  key usage         : Key Cert Sign, CRL Sign

DigiCert Global Root CA
947 byte certificate: DigiCert Global Root CA
  cert. version     : 3
  serial number     : 08:3B:E0:56:90:42:46:B1:A1:75:6A:C9:59:91:C7:4A
  issuer name       : C=US, O=DigiCert Inc, OU=www.digicert.com, CN=DigiCert Global Root CA
  subject name      : C=US, O=DigiCert Inc, OU=www.digicert.com, CN=DigiCert Global Root CA
  issued  on        : 2006-11-10 00:00:00
  expires on        : 2031-11-10 00:00:00
  signed using      : RSA with SHA1
  RSA key size      : 2048 bits
  basic constraints : CA=true
  key usage         : Digital Signature, Key Cert Sign, CRL Sign

ISRG X1 CA
1391 byte certificate: ISRG X1 CA
  cert. version     : 3
  serial number     : 82:10:CF:B0:D2:40:E3:59:44:63:E0:BB:63:82:8B:00
  issuer name       : C=US, O=Internet Security Research Group, CN=ISRG Root X1
  subject name      : C=US, O=Internet Security Research Group, CN=ISRG Root X1
  issued  on        : 2015-06-04 11:04:38
  expires on        : 2035-06-04 11:04:38
  signed using      : RSA with SHA-256
  RSA key size      : 4096 bits
  basic constraints : CA=true
  key usage         : Key Cert Sign, CRL Sign

Starfield Class 2 CA
1043 byte certificate: Starfield Class 2 CA
  cert. version     : 3
  serial number     : 00
  issuer name       : C=US, O=Starfield Technologies, Inc., OU=Starfield Class 2 Certification Authority
  subject name      : C=US, O=Starfield Technologies, Inc., OU=Starfield Class 2 Certification Authority
  issued  on        : 2004-06-29 17:39:16
  expires on        : 2034-06-29 17:39:16
  signed using      : RSA with SHA1
  RSA key size      : 2048 bits
  basic constraints : CA=true

USERTrust RSA Certification Authority
1506 byte certificate: USERTrust RSA Certification Authority
  cert. version     : 3
  serial number     : 01:FD:6D:30:FC:A3:CA:51:A8:1B:BC:64:0E:35:03:2D
  issuer name       : C=US, ST=New Jersey, L=Jersey City, O=The USERTRUST Network, CN=USERTrust RSA Certification Authority
  subject name      : C=US, ST=New Jersey, L=Jersey City, O=The USERTRUST Network, CN=USERTrust RSA Certification Authority
  issued  on        : 2010-02-01 00:00:00
  expires on        : 2038-01-18 23:59:59
  signed using      : RSA with SHA-384
  RSA key size      : 4096 bits
  basic constraints : CA=true
  key usage         : Key Cert Sign, CRL Sign

isrgrootx1.pem
1391 byte certificate: isrgrootx1.pem
  cert. version     : 3
  serial number     : 82:10:CF:B0:D2:40:E3:59:44:63:E0:BB:63:82:8B:00
  issuer name       : C=US, O=Internet Security Research Group, CN=ISRG Root X1
  subject name      : C=US, O=Internet Security Research Group, CN=ISRG Root X1
  issued  on        : 2015-06-04 11:04:38
  expires on        : 2035-06-04 11:04:38
  signed using      : RSA with SHA-256
  RSA key size      : 4096 bits
  basic constraints : CA=true
  key usage         : Key Cert Sign, CRL Sign

r4
525 byte certificate: r4
  cert. version     : 3
  serial number     : 02:03:E5:C0:68:EF:63:1A:9C:72:90:50:52
  issuer name       : C=US, O=Google Trust Services LLC, CN=GTS Root R4
  subject name      : C=US, O=Google Trust Services LLC, CN=GTS Root R4
  issued  on        : 2016-06-22 00:00:00
  expires on        : 2036-06-22 00:00:00
  signed using      : ECDSA with SHA384
  EC key size       : 384 bits
  basic constraints : CA=true
  key usage         : Digital Signature, Key Cert Sign, CRL Sign

root-r1.crt
1371 byte certificate: root-r1.crt
  cert. version     : 3
  serial number     : 02:03:E5:93:6F:31:B0:13:49:88:6B:A2:17
  issuer name       : C=US, O=Google Trust Services LLC, CN=GTS Root R1
  subject name      : C=US, O=Google Trust Services LLC, CN=GTS Root R1
  issued  on        : 2016-06-22 00:00:00
  expires on        : 2036-06-22 00:00:00
  signed using      : RSA with SHA-384
  RSA key size      : 4096 bits
  basic constraints : CA=true
  key usage         : Digital Signature, Key Cert Sign, CRL Sign

Thanks

**Comment by alojz-gomola** [comment]
I have 
  serial number     : 02:00:00:B9
  serial number     : 08:3B:E0:56:90:42:46:B1:A1:75:6A:C9:59:91:C7:4A
  serial number     : 82:10:CF:B0:D2:40:E3:59:44:63:E0:BB:63:82:8B:00
  serial number     : 00
  serial number     : 01:FD:6D:30:FC:A3:CA:51:A8:1B:BC:64:0E:35:03:2D
  serial number     : 00
  serial number     : 02:03:BC:50:A3:27:53:F0:91:80:22:ED:F1
  serial number     : 02:03:E5:C0:68:EF:63:1A:9C:72:90:50:52

You have
serial number : 02:00:00:B9
serial number : 08:3B:E0:56:90:42:46:B1:A1:75:6A:C9:59:91:C7:4A
serial number : 82:10:CF:B0:D2:40:E3:59:44:63:E0:BB:63:82:8B:00
serial number : 00
serial number : 01:FD:6D:30:FC:A3:CA:51:A8:1B:BC:64:0E:35:03:2D
serial number : 82:10:CF:B0:D2:40:E3:59:44:63:E0:BB:63:82:8B:00
serial number : 02:03:E5:C0:68:EF:63:1A:9C:72:90:50:52
serial number : 02:03:E5:93:6F:31:B0:13:49:88:6B:A2:17

Seems like you miss two of mine and have one extra and one duplicate. 

The ones I have that you don’t are these: 

gdroot-g2
969 byte certificate: gdroot-g2
  cert. version     : 3
  serial number     : 00
  issuer name       : C=US, ST=Arizona, L=Scottsdale, O=GoDaddy.com, Inc., CN=Go Daddy Root Certificate Authority - G2
  subject name      : C=US, ST=Arizona, L=Scottsdale, O=GoDaddy.com, Inc., CN=Go Daddy Root Certificate Authority - G2
  issued  on        : 2009-09-01 00:00:00
  expires on        : 2037-12-31 23:59:59
  signed using      : RSA with SHA-256
  RSA key size      : 2048 bits
  basic constraints : CA=true
  key usage         : Key Cert Sign, CRL Sign

google
1424 byte certificate: google
  cert. version     : 3
  serial number     : 02:03:BC:50:A3:27:53:F0:91:80:22:ED:F1
  issuer name       : C=US, O=Google Trust Services LLC, CN=GTS Root R1
  subject name      : C=US, O=Google Trust Services LLC, CN=GTS CA 1P5
  issued  on        : 2020-08-13 00:00:42
  expires on        : 2027-09-30 00:00:42
  signed using      : RSA with SHA-256
  RSA key size      : 2048 bits
  basic constraints : CA=true, max_pathlen=0
  key usage         : Digital Signature, Key Cert Sign, CRL Sign
  ext key usage     : TLS Web Server Authentication, TLS Web Client Authentication

**Comment by Julienhelme** [comment]
OK thanks for that.
So I got rid of the duplcates which seemed to have been a built in cert and the isrgrootx1.pem recommended by the documentation.
And got rid of the google r1 just leaving the the godaddy one you have and it has started working. The google r1 on it's own gave the same error
I don't pretend to know what is happening there but would like to know.
So all I have in the trustedca directory is the  gdroot-g2.crt and my certs are

Baltimore CyberTrust Root CA
891 byte certificate: Baltimore CyberTrust Root CA
  cert. version     : 3
  serial number     : 02:00:00:B9
  issuer name       : C=IE, O=Baltimore, OU=CyberTrust, CN=Baltimore CyberTrust Root
  subject name      : C=IE, O=Baltimore, OU=CyberTrust, CN=Baltimore CyberTrust Root
  issued  on        : 2000-05-12 18:46:00
  expires on        : 2025-05-12 23:59:00
  signed using      : RSA with SHA1
  RSA key size      : 2048 bits
  basic constraints : CA=true, max_pathlen=3
  key usage         : Key Cert Sign, CRL Sign

DigiCert Global Root CA
947 byte certificate: DigiCert Global Root CA
  cert. version     : 3
  serial number     : 08:3B:E0:56:90:42:46:B1:A1:75:6A:C9:59:91:C7:4A
  issuer name       : C=US, O=DigiCert Inc, OU=www.digicert.com, CN=DigiCert Global Root CA
  subject name      : C=US, O=DigiCert Inc, OU=www.digicert.com, CN=DigiCert Global Root CA
  issued  on        : 2006-11-10 00:00:00
  expires on        : 2031-11-10 00:00:00
  signed using      : RSA with SHA1
  RSA key size      : 2048 bits
  basic constraints : CA=true
  key usage         : Digital Signature, Key Cert Sign, CRL Sign

ISRG X1 CA
1391 byte certificate: ISRG X1 CA
  cert. version     : 3
  serial number     : 82:10:CF:B0:D2:40:E3:59:44:63:E0:BB:63:82:8B:00
  issuer name       : C=US, O=Internet Security Research Group, CN=ISRG Root X1
  subject name      : C=US, O=Internet Security Research Group, CN=ISRG Root X1
  issued  on        : 2015-06-04 11:04:38
  expires on        : 2035-06-04 11:04:38
  signed using      : RSA with SHA-256
  RSA key size      : 4096 bits
  basic constraints : CA=true
  key usage         : Key Cert Sign, CRL Sign

Starfield Class 2 CA
1043 byte certificate: Starfield Class 2 CA
  cert. version     : 3
  serial number     : 00
  issuer name       : C=US, O=Starfield Technologies, Inc., OU=Starfield Class 2 Certification Authority
  subject name      : C=US, O=Starfield Technologies, Inc., OU=Starfield Class 2 Certification Authority
  issued  on        : 2004-06-29 17:39:16
  expires on        : 2034-06-29 17:39:16
  signed using      : RSA with SHA1
  RSA key size      : 2048 bits
  basic constraints : CA=true

USERTrust RSA Certification Authority
1506 byte certificate: USERTrust RSA Certification Authority
  cert. version     : 3
  serial number     : 01:FD:6D:30:FC:A3:CA:51:A8:1B:BC:64:0E:35:03:2D
  issuer name       : C=US, ST=New Jersey, L=Jersey City, O=The USERTRUST Network, CN=USERTrust RSA Certification Authority
  subject name      : C=US, ST=New Jersey, L=Jersey City, O=The USERTRUST Network, CN=USERTrust RSA Certification Authority
  issued  on        : 2010-02-01 00:00:00
  expires on        : 2038-01-18 23:59:59
  signed using      : RSA with SHA-384
  RSA key size      : 4096 bits
  basic constraints : CA=true
  key usage         : Key Cert Sign, CRL Sign

gdroot-g2.crt
969 byte certificate: gdroot-g2.crt
  cert. version     : 3
  serial number     : 00
  issuer name       : C=US, ST=Arizona, L=Scottsdale, O=GoDaddy.com, Inc., CN=Go Daddy Root Certificate Authority - G2
  subject name      : C=US, ST=Arizona, L=Scottsdale, O=GoDaddy.com, Inc., CN=Go Daddy Root Certificate Authority - G2
  issued  on        : 2009-09-01 00:00:00
  expires on        : 2037-12-31 23:59:59
  signed using      : RSA with SHA-256
  RSA key size      : 2048 bits
  basic constraints : CA=true
  key usage         : Key Cert Sign, CRL Sign

But err thanks. After a couple of days of faffing and trying to work it all out it is now working.
I don't know if it's a fluke but would like to know why the godaddy cert works and the google ones don't?
That internio ovms-link github documentaion needs an update to be more installer friendly and direct users to the right certs straight away.
I have not found anywhere that describes how to do the editing properly  in the OVMS weserver editor. I can do it now but it's been a painful process.
