### ISSUE TITLE
Nissan Leaf live data issue

### ISSUE THREAD

**Issue by szakal333** [iternio/ovms-link#13]
Hi. I followed the instructions, ABRP is not receiving live data from OVMS for some reason. I noticed the following errors in the console. There is no problem when transferring data with Feaf Spy. Can you help me solve this problem?
![OVMS (1)](https://github.com/iternio/ovms-link/assets/134951212/f82bb0fa-eea6-4276-8468-9279597e0c7e)

**Comment by szakal333** [comment]
Managed to fix it myself. Thanks for your help :D

**Comment by dteirney** [comment]
For posterity, what was the fix?

**Comment by szakal333** [comment]
I used the "config list usr" command to check the current configuration. I found 2 problems. The "abrp.car_model" and "abrp.user_token" parameters did not match because I left the "<>" characters when entering it. I generated a new ABRP token and entered the "config set usr abrp.user_token" command without the "<>" characters, and also re-saved the entire script in OVMS. I also changed the car model with the command "config set usr abrp.car_model" to LEAF 40 (I changed the battery from 24 to 40, in ABRP I had model 40 selected). After these procedures, communication started correctly. However, I have a problem with reading the temperature by OVMS. After changing the battery from 24 to 40 OVMS stopped seeing the battery temperature, although LEAF SPY sees the temperature correctly. Can you help me fix it?

**Comment by dteirney** [comment]
What value for the battery temperature shows up through the `metrics list` message as described at https://docs.openvehicles.com/en/latest/userguide/metrics.html

This ABRP plugin pushes metrics reported by OVMS through to ABRP. If those metrics are incorrect, then best to raise an issue with OVMS.

**Comment by szakal333** [comment]
m.egpio.input                            0;1;2;3;4;5;6;7;8;9
m.egpio.monitor
m.egpio.output                           3;4;5;6;7;8;9
m.freeram                                3479948
m.hardware                               OVMS WIFI BLE BT cores=2 rev=ESP32/1; MODEM SIM5360
m.monotonic                              81406Sec
m.net.mdm.iccid                          8948011620234066110
m.net.mdm.mode                           WCDMA;Online
m.net.mdm.model                          35316B12SIM5360E
m.net.mdm.netreg                         RegisteredHome
m.net.mdm.network                        Plus
m.net.mdm.sq                             -105dBm
m.net.provider                           Plus
m.net.sq                                 -105dBm
m.net.type                               modem
m.net.wifi.network                       CATS61
m.net.wifi.sq                            -127dBm
m.obdc2ecu.on                            yes
m.serial
m.tasks                                  18
m.time.utc                               1686389268Sec
m.version                                3.3.003-489-g0f16f531/ota_1/edge (build idf v3.3.4-849-g6e214dc335 Jun  3 2023 13:15:09)
s.v2.connected                           yes
s.v2.peers                               1
s.v3.connected
s.v3.peers
v.b.12v.current
v.b.12v.voltage                          12.28V
v.b.12v.voltage.alert
v.b.12v.voltage.ref                      12.49V
v.b.c.temp
v.b.c.temp.alert
v.b.c.temp.dev.max
v.b.c.temp.max
v.b.c.temp.min
v.b.c.voltage                            4.052;4.057;4.053;4.057;4.054;4.057;4.051;4.055;4.052;4.055;4.052;4.064;4.056;4.056;4.052;4.057;4.051;4.056;4.054;4.057;4.052;4.057;4.051;4.054;4.054;4.055;4.055;4.057;4.053;4.054;4.053;4.056;4.051;4.054;4.054;4.055;4.052;4.054;4.055;4.055;4.055;4.055;4.054;4.053;4.054;4.054;4.052;4.054;4.056;4.065;4.052;4.066;4.051;4.064;4.054;4.055;4.059;4.064;4.06;4.056;4.051;4.068;4.059;4.058;4.049;4.066;4.059;4.068;4.059;4.067;4.06;4.057;4.05;4.061;4.049;4.058;4.053;4.063;4.054;4.061;4.048;4.06;4.049;4.058;4.055;4.06;4.054;4.063;4.057;4.063;4.057;4.064;4.058;4.063;4.052;4.056V
v.b.c.voltage.alert                      0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0
v.b.c.voltage.dev.max                    -0.00554;-0.00921;-0.00618;-0.0082;0.00516;-0.00507;-0.00783;-0.00928;-0.00664;-0.00607;-0.00725;0.01455;-0.0065;-0.00701;-0.0075;-0.00785;-0.01083;-0.01086;0.00563;-0.01018;-0.00656;-0.00785;-0.0067;-0.00785;-0.00529;-0.0062;-0.00524;-0.00674;-0.00469;-0.00828;-0.00615;-0.00482;-0.00628;-0.00785;-0.0037;-0.00621;-0.0075;-0.0072;0.00484;-0.00684;-0.00623;-0.00501;-0.00883;-0.00942;-0.00583;-0.00684;-0.00683;-0.00628;0.00772;0.0195;0.00732;0.0185;-0.00718;0.01677;-0.00735;-0.00698;0.01815;0.0165;0.01916;-0.00898;0.00972;0.01977;0.02216;0.01076;0.01072;0.01777;0.01916;0.01977;0.02016;0.01777;0.0208;-0.00847;-0.01045;-0.01121;-0.0115;-0.01521;0.00929;-0.01028;0.01115;-0.01085;-0.01289;-0.01421;-0.01124;-0.01228;0.00894;-0.00928;0.00826;0.00894;0.01015;0.00775;0.00857;0.00965;0.01036;0.00918;-0.0082;-0.01084V
v.b.c.voltage.max                        4.052;4.057;4.053;4.057;4.056;4.057;4.052;4.055;4.053;4.055;4.053;4.064;4.056;4.056;4.055;4.057;4.053;4.056;4.055;4.057;4.054;4.057;4.052;4.054;4.055;4.055;4.055;4.057;4.056;4.054;4.054;4.057;4.051;4.054;4.054;4.055;4.052;4.054;4.055;4.055;4.055;4.055;4.054;4.053;4.054;4.054;4.052;4.054;4.056;4.065;4.055;4.066;4.053;4.064;4.054;4.055;4.06;4.065;4.061;4.056;4.053;4.069;4.066;4.059;4.056;4.066;4.064;4.068;4.064;4.067;4.065;4.058;4.056;4.061;4.058;4.058;4.061;4.064;4.062;4.062;4.057;4.06;4.056;4.058;4.367;4.061;4.06;4.063;4.06;4.063;4.623;4.064;4.367;4.064;4.367;4.056V
v.b.c.voltage.min                        3.612;3.611;3.614;3.612;3.614;3.616;3.612;3.612;3.613;3.614;3.613;3.618;3.613;3.615;3.612;3.614;3.612;3.613;3.616;3.613;3.613;3.614;3.613;3.614;3.613;3.617;3.613;3.618;3.616;3.613;3.614;3.615;3.614;3.613;3.616;3.615;3.613;3.615;3.615;3.615;3.614;3.616;3.613;3.613;3.613;3.613;3.612;3.614;3.612;3.617;3.611;3.617;3.61;3.619;3.61;3.615;3.616;3.617;3.614;3.613;3.61;3.616;3.614;3.613;3.612;3.616;3.613;3.617;3.616;3.617;3.616;3.613;3.609;3.609;3.607;3.608;3.609;3.61;3.608;3.609;3.609;3.609;3.607;3.61;3.61;3.611;3.611;3.613;3.61;3.613;3.612;3.614;3.611;3.613;3.609;3.611V
v.b.cac
v.b.consumption                          0kWh/100km
v.b.coulomb.recd
v.b.coulomb.recd.total
v.b.coulomb.used
v.b.coulomb.used.total
v.b.current                              0A
v.b.energy.recd                          1.06971kWh
v.b.energy.recd.total
v.b.energy.used                          3.23246kWh
v.b.energy.used.total
v.b.health
v.b.p.level.avg
v.b.p.level.max
v.b.p.level.min
v.b.p.level.stddev
v.b.p.temp.avg
v.b.p.temp.max
v.b.p.temp.min
v.b.p.temp.stddev
v.b.p.temp.stddev.max                    0°C
v.b.p.voltage.avg                        4.05624V
v.b.p.voltage.grad                       0.00493V
v.b.p.voltage.max                        4.068V
v.b.p.voltage.min                        4.048V
v.b.p.voltage.stddev                     0.00454V
v.b.p.voltage.stddev.max                 0.00766302V
v.b.power                                0kW
v.b.range.est                            232.018km
v.b.range.full                           272.467km
v.b.range.ideal                          234.584km
v.b.range.speed
v.b.soc                                  85.1546%
v.b.soh
v.b.temp
v.b.voltage                              389V
v.c.12v.current
v.c.12v.power
v.c.12v.temp
v.c.12v.voltage
v.c.charging                             no
v.c.climit                               0A
v.c.current                              0A
v.c.duration.full                        125Min
v.c.duration.range
v.c.duration.soc                         0Min
v.c.efficiency                           100%
v.c.kwh                                  18.4846kWh
v.c.kwh.grid
v.c.kwh.grid.total
v.c.limit.range                          0km
v.c.limit.soc                            85%
v.c.mode
v.c.pilot                                yes
v.c.power                                0kW
v.c.state                                timerwait
v.c.substate                             scheduledstop
v.c.temp
v.c.time                                 0Sec
v.c.timermode
v.c.timerstart
v.c.type                                 type1
v.c.voltage                              0V
v.d.cp                                   yes
v.d.fl                                   no
v.d.fr                                   no
v.d.hood
v.d.rl                                   no
v.d.rr                                   no
v.d.trunk                                no
v.e.alarm
v.e.aux12v
v.e.awake                                no
v.e.c.config
v.e.c.login
v.e.cabinfan                             0%
v.e.cabinfanlimit                        7
v.e.cabinintake
v.e.cabinsetpoint                        0°C
v.e.cabintemp                            20°C
v.e.cabinvent                            off
v.e.charging12v                          no
v.e.cooling                              no
v.e.drivemode
v.e.drivetime                            0Sec
v.e.footbrake                            21.5827%
v.e.gear                                 0
v.e.handbrake                            no
v.e.headlights                           no
v.e.heating                              no
v.e.hvac                                 no
v.e.locked                               yes
v.e.on                                   no
v.e.parktime                             49007Sec
v.e.regenbrake
v.e.serv.range
v.e.serv.time
v.e.temp                                 23.5°C
v.e.throttle                             0%
v.e.valet
v.g.climit                               0A
v.g.current                              0A
v.g.duration.empty
v.g.duration.range
v.g.duration.soc
v.g.efficiency
v.g.generating                           no
v.g.kwh
v.g.kwh.grid
v.g.kwh.grid.total
v.g.limit.range
v.g.limit.soc
v.g.mode
v.g.pilot                                no
v.g.power                                0kW
v.g.state                                stopped
v.g.substate                             stopped
v.g.temp
v.g.time                                 0Sec
v.g.timermode
v.g.timerstart
v.g.type
v.g.voltage                              0V
v.i.efficiency                           100%
v.i.power                                0kW
v.i.temp                                 25.5556°C
v.m.rpm                                  0
v.m.temp                                 27.2222°C
v.p.acceleration
v.p.altitude                             
v.p.direction                            
v.p.gpshdop                              1
v.p.gpslock                              yes
v.p.gpsmode                              AA
v.p.gpsspeed                             0km/h
v.p.gpssq                                100%
v.p.gpstime                              1686389268Sec
v.p.latitude                             
v.p.location
v.p.longitude                            
v.p.odometer                             149817km
v.p.satcount                             11
v.p.speed                                0km/h
v.p.trip
v.p.valet.distance
v.p.valet.latitude
v.p.valet.longitude
v.t.alert
v.t.health
v.t.pressure                             2.46488;2.46488;2.53382;2.48211bar
v.t.temp
v.type                                   NL
v.vin                                    1N4AZ0CP4DC408210
xnl.bms.balancing                        1;3;5;6;7;9;11;13;14;15;16;17;19;21;22;23;24;25;27;28;29;31;33;34;35;37;39;41;43;45;47
xnl.bms.temp.int
xnl.bms.thermistor
xnl.cc.fan.only                          no
xnl.cc.remotecool                        no
xnl.cc.remoteheat                        no
xnl.cc.rqinprogress                      no
xnl.v.b.charge.limit                     102.3kW
xnl.v.b.e.available                      33.04kWh
xnl.v.b.e.capacity                       18.4kWh
xnl.v.b.gids                             413
xnl.v.b.heatergranted                    no
xnl.v.b.heaterpresent                    no
xnl.v.b.heatrequested                    no
xnl.v.b.hx                               0
xnl.v.b.max.gids                         413
xnl.v.b.output.limit                     125kW
xnl.v.b.range.instrument                 79km
xnl.v.b.regen.limit                      6kW
xnl.v.b.soc.instrument                   88%
xnl.v.b.soc.newcar                       85.1546%
xnl.v.b.soc.nominal                      84.4%
xnl.v.b.soh.instrument                   97%
xnl.v.b.soh.newcar                       0%
xnl.v.b.type                             0
xnl.v.c.chargebars                       0
xnl.v.c.chargeminutes3kW                 0
xnl.v.c.count.l0l1l2                     77
xnl.v.c.count.qc                         41
xnl.v.c.duration                         27;0;64;0;0Min
xnl.v.c.event.notification               reset
xnl.v.c.event.reason
xnl.v.c.limit.reason                     normal
xnl.v.c.quick                            61
xnl.v.c.state.previous                   timerwait
xnl.v.e.hvac.auto                        no

**Comment by dteirney** [comment]
v.b.temp is not valued based on that metrics list, so no temp is going through to ABRP. Sorry, not sure why that wouldn't be showing up. Try the Nissan Leaf part of the OVMS forums for further guidance. Perhaps this is you there? https://www.openvehicles.com/node/3631
