### ISSUE TITLE
Script sends vehicle parameters that are not supported by vehicle

### ISSUE THREAD

**Issue by kezarjg** [iternio/ovms-link#16]
The current script has no checking to make sure metrics are supported by the OVMS vehicle module before creating the telemetry object.

**Comment by kezarjg** [comment]
The next version of OVMS has a new new DukTape function (OvmsMetrics.HasValue) that can be used to add functionality to to the script to confirm it is in use before adding it to the telemetry object.

**Comment by dteirney** [comment]
With the current implementation, if the standardized OVMS metric doesn't return a value, it's intended to be dropped from the payload sent to ABRP. Which specific metric was being sent to ABRP that wasn't supported?
