### ISSUE TITLE
Easier ways to activate ABRP plugin? 

### ISSUE THREAD

**Issue by glynhudson** [iternio/ovms-link#2]
Typing `script eval abrp.send(1)` command into the OVMS app while driving is not a very user friendly way to enable OVMS>ABRP integration.

Would it possible to use the [HTTP API](https://docs.openvehicles.com/en/latest/protocol_httpapi/index.html) to send msg commands to the OVMS module, e.g to trigger a custom ABRP script? 

Or maybe use send a [OVMS Android app Intent](https://github.com/openvehicles/Open-Vehicle-Android/wiki/SendCommand-Broadcast-Intent-data) message using something like to Tasker to send the command to start the ABRP integration. 

I see mentioned in the latest version V1.4 that "This version uses the embedded GSM of OVMS, so there's an impact on data consumption", does this mean ABRP integration can be left running the whole time without hammering data consumption?

**Comment by dexterbg** [comment]
See https://github.com/openvehicles/Open-Vehicle-Monitoring-System-3/issues/655#issuecomment-940285976

**Comment by Edwintenhaaf** [comment]
@glynhudson Or you can also let it autostart by adding it to /store/scripts/ovmsmain.js
Because the new version of the script will stop sending if the car does not move.

abrp = require("sendlivedata2abrp");
abrp.send(1);

**Comment by jason-abrp** [comment]
I personally run my OVMS on auto-start, and have seen no real impacts on the 12V battery life.  I would welcome any improvements folks want to make to the dynamic sending sequences to make that even better.

**Comment by dteirney** [comment]
FWIW: I just have this plugin autostart as well. A number of the changes in the 2.0 release significantly reduce the amount of traffic that the plugin sends to ABRP.

**Comment by jason-abrp** [comment]
Closing, though I am open to ideas to simplify operation of the plugin.
