### ISSUE TITLE
Update OVMS docs page

### ISSUE THREAD

**Issue by glynhudson** [iternio/ovms-link#3]
Would it be a good idea to update the OVMS docs page to point to this git repo and the latest version of this scrip? https://docs.openvehicles.com/en/latest/plugin/abrp/README.html?highlight=ABRP#abrp-abetterrouteplanner-com

The docs page is still showing an older V1.2 version.

I'm happy to try and make a PR for this if you're happy?

**Comment by dteirney** [comment]
I've got a PR up in the OVMS repo to point the docs for the ABRP plugin to this repository. https://github.com/openvehicles/Open-Vehicle-Monitoring-System-3/pull/718

**Comment by jason-abrp** [comment]
Closing as the PR is merged.
