### ISSUE TITLE
Feedback on options to reduce bandwidth to ABRP

### ISSUE THREAD

**Issue by dteirney** [iternio/ovms-link#4]
Hi @jason-abrp, I've been using ABRP for a few long trips recently and now with the calibration set manually it's doing a great job at estimating the state of charge along the way and therefore suggesting sensible charging options. However, we've been burning through the pay per MB mobile data plan for the hologram SIM card in the OVMS hardware.

I've reviewed the code and found a few ways to reduce it based on a couple of weeks of logs but wanted your opinion from the view of what ABRP needs to do its job well (and based on the information I feel would be useful based on the live data I've been reviewing in ABRP)

* A lot of the ARBP update traffic based on the OVMS logs was due to subtle power changes while charging to 100% on a Level 2 charger, which takes quite a long time. Probably only useful to update ABRP if the power changes by more than 1 kW or the SOC changes. Perhaps a periodic update for the amount of charge that has been consumed for the charge session.
* A lot of the traffic was also sent every 10 seconds if the speed or power changed while driving. Based on the ABRP API docs this is probably related to calibration, which I've found to be quite a long way off so have set it manually in ABRP based on a slight reduction of the car's own average km/kWh estimate. Is there any value in only sending the telemetry data every 10 seconds if the vehicle speed is, say, > 90 kph which would imply cruising along a motorway or similar? It's not obvious how updates being sent when crawling in traffic or in stop and go traffic around the city would be useful for guessing the 110 kph power consumption estimate. Would prefer to avoid that bandwidth if that "every 10 seconds" telemetry data is simply going to be discarded by ABRP for the purposes of calibration if the vehicle speed is too low. 

If I make any changes I'd probably look at a fairly significant refactoring of this plugin for ABRP. There are a few metrics not being provided to ABRP that OVMS appears to have so I'd add them as well.

**Comment by jason-abrp** [comment]
These are some great ideas.

> due to subtle power changes while charging to 100% on a Level 2 charger  

I like the idea to only update for large changes while charging.  Power delta > 1kW or SoC by 1%p would work well I think.

> sent every 10 seconds if the speed or power changed while driving

You are correct that this is for calibration.  We need high-frequency updates to adapt the calibration.  I am concerned that the calibration doesn't seem to be working, though.  It works very well for other data sources, so that means we're getting either incorrect power or speed readings from OVMS.  Could you review the in-motion data for some recent drives to see if we can pinpoint where it's going wrong?

The point of regular data points is to recalibrate on the fly to changing conditions.  If there's a sudden headwind, or temperature drop, we can see that in the incoming power data, and adjust the plan accordingly.  But to ensure it's not a fluke, we need consistent data to show a clear trend. The slower the data comes in, the slower we are to react and adjust the plan.

I will not have time to do these changes in the near future (I will be away from my OVMS vehicle for some time), but I welcome any rewrites you'd like to make and submit as a Pull Request!

**Comment by dteirney** [comment]
> I am concerned that the calibration doesn't seem to be working, though. It works very well for other data sources, so that means we're getting either incorrect power or speed readings from OVMS. Could you review the in-motion data for some recent drives to see if we can pinpoint where it's going wrong?

I've got logs from several days of travel a while back which would have still been sending every 10 seconds. Not sure how the algorithm in ABRP works but it's presumably quite challenging with point-in-time windows of data across a quite variable range of information with up and downhill travel probably influencing power consumption changes more than variations in headwind etc. Not many places that we would have had consistently flat travel so that might be related. Happy to provide filtered logs if useful but not sure I can confirm if the speed or power information was accurate. The currently calibrated reference consumption is 5.25 km/kWh @ 110kph (was lower initially) but with it manually set to 6.25 we're getting much more accurate results. Give or take only 15% too conservative but makes a difference about the charging locations suggested. Don't often get to travel at 110 kph on roads around New Zealand so that might be a factor as well (obviously much more efficient per distance unit when travelling at a slower speed).

Unrelated. How often does telemetry information need to be sent to ABRP for the vehicle to be considered connected? Looking to confirm what telemetry changes should influence how frequently the local information is sent off to ABRP.

**Comment by jason-abrp** [comment]
> I've got logs from several days of travel a while back which would have still been sending every 10 seconds. Not sure how the algorithm in ABRP works but it's presumably quite challenging with point-in-time windows of data across a quite variable range of information with up and downhill travel probably influencing power consumption changes more than variations in headwind etc.

We do account for all of that with the calibration algorithm, we subtract out the conditions of the day (including weather and elevation changes).

If you like, shoot me an email and we can take a deeper look at figuring out where the telemetry is going wrong.  Perhaps the GPS data is too out of synch with the telemetry read over OBD, since we don't get called that often.

>Unrelated. How often does telemetry information need to be sent to ABRP for the vehicle to be considered connected? Looking to confirm what telemetry changes should influence how frequently the local information is sent off to ABRP.

It varies by source, for OVMS we use the default value, 3 minutes, before we consider it stale.  We could change that, other slower telemetry sources are set as high as 30 minutes.  We also need to consider changing the verbiage, since you might not actually be disconnected, just stale, and I think it leads to some confusion.

**Comment by dteirney** [comment]
@jason-abrp a fork that has most of the changes I want to make is up at https://github.com/dteirney/ovms-link

Fairly significant rewrite but I feel that it's quite a bit easier to follow what is happening. We'll be testing this for a while to see if it behaves well with respect to the Hologram bandwidth use. An additional modification could be done to average the power recorded at 1-second intervals and then post the averaged power with the other updates every 10 seconds when travelling over 70 kph. Let me know if there's likely to be any benefit to the accuracy of the calibration with that approach.

**Comment by jason-abrp** [comment]
@dteirney - sounds great to me! I'm happy to merge once you're happy with it.

If you want to do a pre-filtered power reading, I would suggest a median power value, as the power readings can be quite variable.  An average reading will likely be somewhat far from the truth.  Most important is that we get the speed reading from the same instant as the power reading (or as close to the same instant as reasonable).

**Comment by dteirney** [comment]
@jason-abrp in terms of the higher resolution capture of the power readings, I thought an average would work quite well if the discrete point in time speed was sent at the end of the period. Primarily because the speed at the end of the period is influenced by the area under the continuous power curve. E.g. the speed at time t10 would be influenced by the power added to the vehicle between t0 and t10. If t0 and t10 are 10 seconds apart and the power is taken at the t0, t1, t2, t3, t4, etc. ... discrete times, I thought that the average of all those power readings would be a good approximation for the average power added in the previous 10 seconds rather than the discrete point in time power reading at t10, which could be quite different if suddenly heading up a hill or regen braking moves the power negative.

I've currently got the calibration speed set to > 30 kph so it's capturing a reasonable amount of data. We'll be doing some driving this weekend so I'll see how the computed km/kWh @ 110 kph pans out. At the moment it's still reading quite a lot lower than what is a good setting to have the estimated SOC at the destination match what actually happens. The averaged km/kWh that the car records for overall driving is currently reading 7.1. The setting that works well in OVMS is 6.25. The current OVMS calibration is < 5.

Not sure if GPS positioning factors into the calculations that OVMS does with the data, I'll pour over some of the data captured this weekend but I've noticed some lat/lng information didn't change between the 10 second pushes to ABRP. Possibly the GPS data doesn't update fast enough? Would that be a contributing factor if that is the case? Is there any other data that influences the callibration data that I should investigate?

**Comment by dteirney** [comment]
Following on from the previous comment, physical braking and the losses from regenerative braking must come into play. Not sure that even averaging power over the 10 seconds is helpful other than to smooth the power since it's massively variable. I'll update the code that we're running to compute both the average power and median across the last 10 seconds. I'm now wondering if you also meant that it would be useful to do the same higher resolution capture of the speed as well, and apply the same statistical smoothing for that as well? Speed not as subject to massive variations but perhaps the same smoothing would be necessary. Any approach can be done and I'm happy to do whatever you think would be most useful for calibration.

**Comment by dteirney** [comment]
@jason-abrp think I've understood the earlier comment. Now I'm recording the speed and power metrics together and returning the matching pair of those based on the median power reading across those collected. I will test that more over the next week.

**Comment by dteirney** [comment]
@jason-abrp been using the current state of the plugin for a while. I've created a PR for the current state of the changes. Going to seek some other testers in the OVMS forums. We've currently got it configured to only send calibration data when travelling over 70 kph. The current calibration for our vehicles is showing about 6.6 km/kWh. I'd been manually using 6.5 for some of our recent trips so that's much closer than the <5 that we'd seen previously.

**Comment by dteirney** [comment]
Also, once this is merged I've got a PR ready to go for the OVMS documentation for the plugin to refer to the README.md document that will exist in this repo to avoid the content in that repo getting out of date.

**Comment by jason-abrp** [comment]
That's great to hear, and the PR looks clean so I've merged it.  Some really good stuff in there.  Thanks for contributing! As thanks I've given you some free premium.
